# https://numtide.github.io/devshell
# https://numtide.github.io/devshell/getting_started.html
[[commands]]
package = "nodejs_20"

[[env]]
name = "PGHOST"
value = "/tmp"

[[env]]
name = "PGDATA"
value = ".pgdata"

[[env]]
name = "PGPORT"
value = "5555"

[devshell]
packages = [
  "postgresql",
]

[[commands]]
name = "initPostgres"
help = "Initialize the Postgres database"
command = """\
  initdb $PGDATA --auth-local=trust --auth-host=trust; \
  echo -e "Use the devshell command 'database:start'"
  """

[serviceGroups.database]
description = "Runs a database in the background"
[serviceGroups.database.services.postgres]
command = "postgres -D $PGDATA -k $PGHOST -p 5555"